### ISSUE TITLE
We have -Lw+Hw=HI, same as (H-L)w=HI, with (H-L)=DA (with D=diag(1./area))

### ISSUE THREAD

**Issue by Sky10086** [elrond79/Pinocchio#2]
We have -Lw+Hw=HI, same as (H-L)w=HI, with (H-L)=DA (with D=diag(1./area))
why the (H-L) equals the DA?

**Comment by elrond79** [comment]
Hey - it's been a long time since I looked at the code / underlying algorithm, and while I had a basic understanding at the time, I was never an expert - this is just some minor tweaks to the code from Ilya Baran et al, here:

http://www.mit.edu/~ibaran/autorig/

In other words - after a brief glance at the comment you're referencing, I don't know / remember. =) You can try reaching out to Ilya Baran if you want.
